-- AlterTable
ALTER TABLE "Cancelled" ADD COLUMN     "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedAt" TIMESTAMP(3),
ALTER COLUMN "setOn" DROP NOT NULL,
ALTER COLUMN "setOn" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "ClosedContractPartner" ADD COLUMN     "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedAt" TIMESTAMP(3),
ALTER COLUMN "setOn" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "NotPossible" ADD COLUMN     "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedAt" TIMESTAMP(3),
ALTER COLUMN "setOn" DROP NOT NULL,
ALTER COLUMN "setOn" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "OrderStatus" ALTER COLUMN "setOn" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Planned" ADD COLUMN     "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedAt" TIMESTAMP(3),
ALTER COLUMN "setOn" DROP NOT NULL,
ALTER COLUMN "setOn" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Postponed" ADD COLUMN     "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedAt" TIMESTAMP(3),
ALTER COLUMN "setOn" DROP NOT NULL,
ALTER COLUMN "setOn" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Received" ADD COLUMN     "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedAt" TIMESTAMP(3),
ALTER COLUMN "setOn" DROP NOT NULL,
ALTER COLUMN "setOn" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Rejected" ADD COLUMN     "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedAt" TIMESTAMP(3),
ALTER COLUMN "setOn" DROP NOT NULL,
ALTER COLUMN "setOn" SET DEFAULT CURRENT_TIMESTAMP;
